baseURL = "https://snyssfx.github.io/" # Hostname (and path) to the root.
languageCode = "en-us"
title = "Gleb Zakharov"
theme = "hugo-coder-portfolio"

defaultcontentlanguage = "en" # The default content language.
paginate = 20 # Default number of pages per page in pagination.
pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "snyssfx-github-io" # Enable or disable Disqus.

[params] # theme parameters
    author = "Gleb Zakharov" # Author's name.
    info = "BACKEND SOFTWARE ENGINEER" # Author's job title or info.
    description = "Gleb Zakharov's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "avatar.jpeg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "💝" # Add footer content
    fixedbarContent = "Email me! " # Add fixedbar content
    fixedbarContentAfter = "snyssfx@gmail.com" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Snyssfx/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/gleb-zakharov-44080215b/"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 4
    url = "https://t.me/snyssfx"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Gleb Zakharov"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        author = "Gleb Zakharov"
        info = "BACKEND SOFTWARE ENGINEER"
        description = "Gleb Zakharov's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "CV"
        weight = 2.0
        url = "cv.pdf"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 3.0
        url = "posts"

    [languages.ru]
        languagename = "Russian"
        title = "Глеб Захаров"

        [languages.ru.params]
            author = "Глеб Захаров"
            description = "Сайт Глеба Захарова"
            keywords = "blog,developer,personal"
            info = "BACKEND SOFTWARE ENGINEER"
            fixedbarContent = "Почта! "

        [languages.ru.menu]

            [[languages.ru.menu.main]]
            name = "обо мне"
            weight = 1.0
            url = "../about"

            [[languages.ru.menu.main]]
            name = "резюме"
            weight = 2.0
            url = "../cv.pdf"

            [[languages.ru.menu.main]]
            name = "посты"
            weight = 3.0
            url = "../posts"

